"""Configuration and utilities for LLM-backed agent integration."""

import os
from dataclasses import dataclass
from typing import Optional

try:
	from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional dependency fallback
	load_dotenv = None

	
if load_dotenv is not None:
	load_dotenv()


@dataclass
class LLMConfig:
	"""Configuration for LLM provider settings."""
	provider: str = "openai"  # "openai" or "anthropic"
	api_key: Optional[str] = None
	scheduler_model: str = "gpt-3.5-turbo"
	explanation_model: str = "gpt-4o-mini"
	temperature: float = 0.7
	max_tokens: int = 1500
	timeout_seconds: int = 60
	enabled: bool = True

	@classmethod
	def from_env(cls) -> "LLMConfig":
		"""Create config from environment variables."""
		legacy_model = os.getenv("LLM_MODEL")
		return cls(
			provider=os.getenv("LLM_PROVIDER", "openai"),
			api_key=os.getenv("OPENAI_API_KEY"),
			scheduler_model=os.getenv("LLM_SCHEDULER_MODEL", legacy_model or "gpt-3.5-turbo"),
			explanation_model=os.getenv("LLM_EXPLANATION_MODEL", legacy_model or "gpt-4o-mini"),
			temperature=float(os.getenv("LLM_TEMPERATURE", "0.7")),
			max_tokens=int(os.getenv("LLM_MAX_TOKENS", "1500")),
			timeout_seconds=int(os.getenv("LLM_TIMEOUT", "60")),
			enabled=os.getenv("LLM_ENABLED", "true").lower() == "true",
		)

	@property
	def model(self) -> str:
		"""Compatibility alias for the scheduler model."""
		return self.scheduler_model

	@model.setter
	def model(self, value: str) -> None:
		"""Keep legacy callers working by setting both model defaults."""
		self.scheduler_model = value
		self.explanation_model = value

	def is_valid(self) -> bool:
		"""Check if config has required settings to make API calls."""
		if not self.enabled:
			return False
		if not self.api_key:
			return False
		if self.provider == "openai":
			return True
		return False


@dataclass
class LLMPromptTemplates:
	"""Prompts for instructing LLMs how to act as agents."""

	@staticmethod
	def explanation_enhancer_prompt(raw_explanations: str) -> str:
		"""Prompt for rewriting technical schedule notes into friendly natural language."""
		return f"""You are a friendly pet care assistant helping a pet owner understand their daily schedule.

Below are technical scheduling notes generated by an automated planner. Rewrite them in 3–5 warm, conversational sentences that a pet owner would enjoy reading.

Rules:
- Use plain language — no jargon like "priority=5", "PLACED_FIRST_OPEN_GAP", or "flexible=False"
- Be specific about the actual task names and times mentioned
- Keep it concise and encouraging
- Do not invent details that are not present in the notes

TECHNICAL NOTES:
{raw_explanations}

Respond with only the rewritten explanation paragraph, no headings or extra text."""

	@staticmethod
	def task_validation_agent_prompt(task_str: str, existing_tasks_str: str) -> str:
		"""Prompt for Task Management Agent to validate and suggest repairs."""
		return f"""You are a Pet Care Task Management Agent. Your job is to validate task payloads and suggest repairs.

Analyze the task below and check for:
1. Positive duration (must be > 0)
2. Valid time window (latest_end > earliest_start)
3. Coherent recurrence rules
4. No duplicates or contradictions with existing tasks

Return your response as a JSON object:
{{
  "is_valid": boolean,
  "violations": [
    {{
      "code": "string (e.g., INVALID_DURATION)",
      "message": "string describing the problem",
      "severity": "string (low, medium, high, critical)",
      "repair_hint": "string with suggested fix"
    }}
  ],
  "repair_suggestions": ["string with specific recommendations"]
}}

TASK TO VALIDATE:
{task_str}

EXISTING TASKS FOR THIS PET:
{existing_tasks_str}

Respond with only valid JSON, no additional text."""


# Global config instance (can be overridden for testing)
_global_llm_config: Optional[LLMConfig] = None


def get_llm_config() -> LLMConfig:
	"""Get or initialize the global LLM config."""
	global _global_llm_config
	if _global_llm_config is None:
		_global_llm_config = LLMConfig.from_env()
	return _global_llm_config


def set_llm_config(config: LLMConfig) -> None:
	"""Override the global LLM config (useful for testing)."""
	global _global_llm_config
	_global_llm_config = config
